#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2020 Alberto Pianon <pianon@array.eu>

MD=`cat -`

MUSTACHE=`sed -n '/---/,/---/p' <<< $MD | grep "^mustache:" | cut -d' ' -f2`

PANDOC="pandoc -f markdown-raw_tex+tex_math_single_backslash --columns 10 --lua-filter=crossref-ordered-list.lua --lua-filter=secgroups.lua --filter=pandoc-crossref --lua-filter=inline-headers.lua -t html"

if [ -z $MUSTACHE ]
then
   pp-include.pl <<< $MD | $PANDOC
else
   pp-include.pl <<< $MD | mustache $MUSTACHE - | $PANDOC
fi
